user_source:
item_source:
dest: models
prediction_dest: predictions
ratings:
model: BasicCBRS
n_workers: 4

dataset:
  name: HybridUserItemSequence
  ratings_filepath: datasets/movielens/train2id.tsv
  graph_filepath:
  user_filepath: embeddings/bert/user-lastlayer.json
  item_filepath: embeddings/bert/item-lastlayer.json
  evaluate: False
  batch_size: 512
  shuffle: False
  seed: 42

parameters:
  epochs: 25
  optimizer:
    lr: 0.001
    beta: 0.9
  metrics: ['accuracy']
  loss: binary_crossentropy