dest: exp
details: try
prediction_dest: predictions
n_workers: 12
seed: 42

model:
  name: gnn.BasicGCN
  embedding_dim: 16
  n_hiddens: !!python/tuple [16, 16, 16]
  l2_regularizer: 1e-4
  # Defines how the final node will be represented from layers (concatenation, sum, mean, last, w-mean)
  # It is overwritten to 'mean' in case of LightGCN
  final_node: 'concatenation'
  # Graph sage
  aggregate: mean
  # LightGCN
  n_layers: 3
  # BasicRS and HybridCBRS
  dense_units: !!python/tuple [64, 32]
  clf_units: !!python/tuple [32, 32]
  # HybridCBRS
  feature_based: False

dataset:
  load_function_name: load_user_item_graph
  # For load_user_item_graph function name
  binary_adjacency: False
  sparse_adjacency: True
  # Basic or Hybrid embeddings datasets
  graph_filepath: embeddings/user-item-properties/768DistMult.json
  bert_user_filepath: embeddings/bert/user-lastlayer.json
  bert_item_filepath: embeddings/bert/item-lastlayer.json
  # For all the datasets
  train_ratings_filepath: datasets/movielens/train2id.tsv
  test_ratings_filepath: datasets/movielens/test2id.tsv
  train_batch_size: 1024
  test_batch_size: 2048
  shuffle: True

parameters:
  epochs: 25
  optimizer:
    name: Adam
    lr: 0.001
    beta: 0.9
  metrics: ['accuracy']
  loss: binary_crossentropy
