user_source:
item_source:
dest: exp
details: just_try
prediction_dest: predictions
ratings:
n_workers: 4

model:
  name: basic.BasicCBRS
  feature_based: False # For HybridCBRS

dataset:
  name: BERTUserItemSequence
  ratings_filepath: datasets/movielens/train2id.tsv
  graph_filepath:
  user_filepath: embeddings/bert/user-lastlayer.json
  item_filepath: embeddings/bert/item-lastlayer.json
  evaluate: False
  batch_size: 512
  shuffle: False
  seed: 42

parameters:
  epochs: 1
  optimizer:
    name: Adam
    lr: 0.001
    beta: 0.9
  metrics: ['accuracy']
  loss: binary_crossentropy